refactor: exact instances of some Option/Result/other combinators
n0-computer/iroh pull request #466
Opened 2022-11-02 20:57 UTC by huitseeker

Tool-aided by [comby-rust](https://github.com/huitseeker/comby-rust).

2022-11-04 15:22 UTC, huitseeker commented
@dignifiedquire the intentional commit of this PR is the [first](https://github.com/n0-computer/iroh/pull/466/commits/a9a83c803e1c013017afc61431c0c916c3f45408), the other one being a standard run of clippy auto-fixes. 

The idea is to simplify the code from verbose pattern-matches to idiomatic standard library combinators they are an exact reimplementation of. My opinions on this are loosely held - if you're not convinced of those idioms being simpler, in part of as a group, I'm happy to amend the PR to your desire, or close it altogether.

2022-11-11 09:41 UTC, matthiasbeyer requested changes

2022-11-11 09:41 UTC, matthiasbeyer commented on iroh-metrics/src/lib.rs
> +    let console_subscriber = (cfg.tokio_console).then_some(console_subscriber::spawn());
```suggestion
    let console_subscriber = cfg.tokio_console.then(console_subscriber::spawn);
```

In the code right now, `console_subscriber::spawn()` is always called, which is probably not what you want, right?

Also, the parentheses around `cfg.tokio_console` are not required!

2022-11-11 09:41 UTC, matthiasbeyer commented on iroh-p2p/src/node.rs
> +        let mut nice_interval = (self.use_dht).then_some(tokio::time::interval(NICE_INTERVAL));
```suggestion
        let mut nice_interval = self.use_dht.then(|| tokio::time::interval(NICE_INTERVAL));
```

2022-11-11 09:41 UTC, matthiasbeyer commented on stores/flatfs/src/flatfs.rs
> +            Ok(entry) => (entry.path().is_file()).then_some(read_file(entry.path())),
```suggestion
            Ok(entry) => entry.path().is_file().then(|| read_file(entry.path())),
```

2022-11-11 09:41 UTC, matthiasbeyer commented on stores/flatfs/src/flatfs.rs
> +            Ok(entry) => (entry.path().is_file()).then_some(key_from_path(entry.path())),
```suggestion
            Ok(entry) => entry.path().is_file().then(|| key_from_path(entry.path())),
```

2022-11-11 09:41 UTC, matthiasbeyer commented on stores/flatfs/src/flatfs.rs
> +            Ok(entry) => (entry.path().is_file()).then_some(KvStats::from_path(entry.path())),
```suggestion
            Ok(entry) => entry.path().is_file().then(|| ̣̣̣KvStats::from_path(entry.path())),
```

2022-11-11 09:41 UTC, matthiasbeyer commented on stores/flatfs/src/flatfs.rs
> +                (entry.path().is_file()).then_some(fs::read(entry.path()).map_err(Into::into))
```suggestion
                entry.path().is_file().then(|| fs::read(entry.path()).map_err(Into::into))
```

2022-11-11 12:48 UTC, huitseeker commented
Thanks for the review @matthiasbeyer! This makes total sense, I'll also amend [the tooling](https://github.com/huitseeker/comby-rust/issues/1) with your comments!

2022-11-11 14:20 UTC, dignifiedquire submitted a review, later dismissed

2022-11-14 20:48 UTC, b5 commented on iroh-metrics/src/lib.rs
> +    let console_subscriber = cfg.tokio_console.then(|| console_subscriber::spawn());
one last bit to placate clippy:
```suggestion
    let console_subscriber = cfg.tokio_console.then(console_subscriber::spawn);
```

2022-11-21 21:31 UTC, b5 commented
thanks @huitseeker!

2022-11-21 21:31 UTC, merged